// packages/react/spinner/src/SpinnerThumb.tsx
import { poly, type CoreProps } from '@klnjs/react-core'
import { useSpinnerContext } from './SpinnerContext'

export type SpinnerThumbProps = CoreProps<
	'circle',
	{
		arc?: number
		angle?: number
		easing?: string
		duration?: number
		cap?: 'butt' | 'round' | 'square'
	}
>

export const SpinnerThumb = ({
	arc: arcProp = 25,
	angle = 0,
	easing,
	duration = 1,
	cap = 'round',
	...otherProps
}: SpinnerThumbProps) => {
	const { width, radius, center, circumference } = useSpinnerContext()

	const arc = (circumference * arcProp) / 100
	const rotate = -90 + angle

	return (
		<poly.circle
			r={radius}
			cx={center}
			cy={center}
			transform={`rotate(${rotate} ${center} ${center})`}
			fill="none"
			stroke="currentColor"
			strokeWidth={width}
			strokeLinecap={cap}
			strokeDasharray={`${arc},${circumference}`}
			{...otherProps}
		>
			<animateTransform
				attributeName="transform"
				dur={`${duration}s`}
				calcMode="spline"
				keySplines={easing}
				type="rotate"
				values={`${rotate} ${center} ${center};${rotate + 360} ${center} ${center}`}
				repeatCount="indefinite"
			/>
		</poly.circle>
	)
}

// packages/svelte/spinner/src/SpinnerThumb.svelte
<script lang="ts">
	import type { CoreProps } from '@klnjs/svelte-core'
	import { getSpinnerContext } from './SpinnerContext'

	type $$Props = CoreProps<
		SVGCircleElement,
		{
			arc?: number
			angle?: number
			easing?: string
			duration?: number
			cap?: 'butt' | 'round' | 'square'
		}
	>

	const context = getSpinnerContext()

	let ref: $$Props['ref']
	let easing: $$Props['easing']
	let arcProp: number = 25
	let angle: number = 0
	let cap: $$Props['cap'] = 'round'
	let duration: number = 1

	$: ({ radius, center, circumference, width } = $context);
	$: arc = (circumference * arcProp) / 100
	$: rotate = -90 + angle

	export { ref, arcProp as arc, easing, angle, cap, duration }
</script>

<circle
	bind:this="{ref}"
	r={radius}
	cx={center}
	cy={center}
	transform={`rotate(${rotate} ${center} ${center})`}
	fill="none"
	stroke="currentColor"
	stroke-width={width}
	stroke-linecap={cap}
	stroke-dasharray={`${arc},${circumference}`}
	{...$$restProps}
>
	<animateTransform
		attributeName="transform"
		dur={`${duration}s`}
		calcMode="spline"
		keySplines={easing}
		type="rotate"
		values={`${rotate} ${center} ${center};${rotate + 360} ${center} ${center}`}
		repeatCount="indefinite"
	/>
</circle>
