// packages/react/spinner/src/Spinner.tsx
import { poly, type CoreProps } from '@klnjs/react-core'
import { SpinnerProvider } from './SpinnerContext'
import { useSpinner, type SpinnerOptions } from './useSpinner'

export type SpinnerProps = CoreProps<'svg', Partial<SpinnerOptions>>

export const Spinner = ({
	size = 24,
	width = 4,
	...otherProps
}: SpinnerProps) => {
	const spinner = useSpinner({
		size,
		width
	})

	return (
		<SpinnerProvider value={spinner}>
			<poly.svg
				xmlns="http://www.w3.org/2000/svg"
				viewBox={`0 0 ${spinner.diameter} ${spinner.diameter}`}
				width={spinner.diameter}
				height={spinner.diameter}
				{...otherProps}
			/>
		</SpinnerProvider>
	)
}

// packages/svelte/spinner/src/Spinner.svelte
<script lang="ts">
	import type { CoreProps } from '@klnjs/svelte-core'
	import { createSpinner, type SpinnerOptions } from '@klnjs/spinner'
	import { createSpinnerContext } from './SpinnerContext'

	type $$Props = CoreProps<SVGElement, Partial<SpinnerOptions>>

	let asChild: $$Props['asChild'] = false
	let ref: $$Props['ref']
	let size: number = 24
	let width: number = 4

	$: spinner = createSpinner({ size, width })

	let context = createSpinnerContext(spinner)

	$: context.set(createSpinner({ size, width }))
	$: ({ diameter } = spinner)

	export { asChild, ref, size, width }
</script>

{#if asChild}
	<slot {...$$restProps} />
{:else}
	<svg
		bind:this="{ref}"
		xmlns="http://www.w3.org/2000/svg"
		viewBox="{`0 0 ${diameter} ${diameter}`}"
		width="{diameter}"
		height="{diameter}"
		{...$$restProps}
	>
		<slot />
	</svg>
{/if}
