// packages/react/avatar/src/AvatarFallback.tsx
import { useState, useEffect } from 'react'
import { poly, forwardRef, type CoreProps } from '@klnjs/react-core'
import { useAvatarContext } from './AvatarContext'

export type AvatarFallbackProps = CoreProps<'div', { delay?: number }>

export const AvatarFallback = forwardRef<'div', AvatarFallbackProps>(
	({ delay, ...otherProps }, forwardedRef) => {
		const { status } = useAvatarContext()

		const [ready, setReady] = useState(delay === undefined)

		useEffect(() => {
			if (delay !== undefined) {
				const timeout = setTimeout(() => setReady(true), delay)

				return () => {
					clearTimeout(timeout)
				}
			}
		}, [delay])

		return ready && status !== 'loaded' ? (
			<poly.div ref={forwardedRef} {...otherProps} />
		) : null
	}
)

// packages/svelte/avatar/src/AvatarFallback.svelte
<script lang="ts">
	import type { CoreProps } from '@klnjs/svelte-core'
	import { getAvatarContext } from './AvatarContext'

	type $$Props = CoreProps<
		HTMLDivElement,
		{
			delay?: number
		}
	>

	const { status } = getAvatarContext()

	let ref: $$Props['ref']
	let delay: $$Props['delay'] = 0
	let ready = delay === 0

	setTimeout(() => (ready = true), delay)

	export { ref, delay }
</script>

{#if ready && $status !== 'loaded'}
	<div bind:this="{ref}" {...$$restProps}>
		<slot />
	</div>
{/if}
