// packages/react/avatar/src/AvatarImage.tsx
import { poly, useChainHandler, type CoreProps } from '@klnjs/react-core'
import { useAvatarContext } from './AvatarContext'

export type AvatarImageProps = CoreProps<'img'>

export const AvatarImage = ({
	src,
	style: styleProp,
	onLoad,
	onLoadStart,
	onError,
	...otherProps
}: AvatarImageProps) => {
	const { status, setStatus } = useAvatarContext()

	const style = {
		display: status !== 'loaded' ? 'none' : undefined,
		...styleProp
	}

	const handleLoad = useChainHandler(onLoad, () => setStatus('loaded'))

	const handleLoadStart = useChainHandler(onLoadStart, () =>
		setStatus('loading')
	)

	const handleError = useChainHandler(onError, () => setStatus('error'))

	return (
		<poly.img
			src={src}
			style={style}
			onLoad={handleLoad}
			onLoadStart={handleLoadStart}
			onError={handleError}
			{...otherProps}
		/>
	)
}

// packages/svelte/avatar/src/AvatarImage.svelte
<script lang="ts">
	import type { HTMLImgAttributes } from 'svelte/elements'
	import { getAvatarContext } from './AvatarContext'

	type AvatarImageProps = HTMLImgAttributes & {
		ref?: HTMLDivElement
		src?: string
		alt: string
	}

	let { status, setStatus } = getAvatarContext()
	let { ref, src, alt, ...otherProps }: AvatarImageProps = $props()
</script>

<img
	bind:this={ref}
	{src}
	{alt}
	style:display={status !== 'loaded' ? 'none' : undefined}
	data-status={status}
	onerror={() => setStatus('error')}
	onload={() => setStatus('loaded')}
	onloadstart={() => setStatus('loading')}
	{...otherProps}
/>
