// packages/svelte/spinner/src/SpinnerTrack.svelte
<script lang="ts">
	import type { CoreProps } from '@klnjs/svelte-core'
	import { getSpinnerContext } from './SpinnerContext'

	type $$Props = CoreProps<SVGCircleElement>

	const context = getSpinnerContext()

	let ref: $$Props['ref']

	$: ({ radius, center, width } = $context)

	export { ref }
</script>

<circle
	bind:this="{ref}"
	r="{radius}"
	cx="{center}"
	cy="{center}"
	fill="none"
	stroke="currentColor"
	stroke-width="{width}"
	{...$$restProps}
></circle>

// packages/react/spinner/src/SpinnerTrack.tsx
import { poly, type CoreProps } from '@klnjs/react-core'
import { useSpinnerContext } from './SpinnerContext'

export type SpinnerTrackProps = CoreProps<'circle'>

export const SpinnerTrack = (props: SpinnerTrackProps) => {
	const { radius, center, width } = useSpinnerContext()

	return (
		<poly.circle
			r={radius}
			cx={center}
			cy={center}
			fill="none"
			stroke="currentColor"
			strokeWidth={width}
			{...props}
		/>
	)
}
