// apps/docs/src/docs/02-components/avatar/avatar.tsx
import { Avatar, AvatarImage, AvatarFallback } from '@klnjs/react-avatar'
import src from './avatar.png'
import classes from './avatar.module.css'

export default () => (
	<Avatar className={classes.avatar}>
		<AvatarImage src={src} className={classes.image} />
		<AvatarFallback delay={5000} className={classes.fallback}>
			RK
		</AvatarFallback>
	</Avatar>
)

// apps/starlight/src/content/docs/components/avatar/avatar.svelte
<script lang="ts">
	import { Avatar, AvatarImage, AvatarFallback } from '@klnjs/svelte-avatar'
	import image from './avatar.png'
	import classes from './avatar.module.css'
</script>
 
<Avatar className={classes.avatar}>
	<AvatarImage src={image.src} className={classes.image} />
	<AvatarFallback className={classes.fallback}>RK</AvatarFallback>
</Avatar>
